apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-istio-controller
  namespace: istio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: istio-istio-controller
  namespace: istio
  labels:
    apps.kubernetes.io/name: istio-istio-controller
spec:
  selector:
    matchLabels:
      apps.kubernetes.io/name: istio-istio-controller
  template:
    metadata:
      labels:
        apps.kubernetes.io/name: istio-istio-controller
      annotations:
        sidecar.istio.io/inject: 'false'
    spec:
      serviceAccountName: istio-istio-controller
      imagePullSecrets:
        - name: k8scc01covidacr-registry-connection
      containers:
      - name: istio-istio-controller
        image: k8scc01covidacr.azurecr.io/istio-istio-controller:8791e2d57fa035acd719086952427e6ec516340e
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istio-istio-controller
rules:
- apiGroups:
    - 'networking.istio.io'
  resources:
    - 'virtualservices'
    - 'destinationrules'
  verbs:
    - watch
    - get
    - list
    - create
    - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: istio-istio-controller
subjects:
- kind: ServiceAccount
  name: istio-istio-controller
  namespace: istio
roleRef:
  kind: ClusterRole
  name: istio-istio-controller
  apiGroup: rbac.authorization.k8s.io
