name: build_and_push_tag
on:
  push:
    tags:
      - "*"

jobs:
  # Any checks that run pre-build
  pre-build-checks:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set environment variables
        shell: bash
        run: |
          echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
          echo "GIT_SHA=${GITHUB_SHA}" >> $GITHUB_ENV
      -
        name: Docker meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: statcan/ingress-istio-controller
          labels: |
            org.opencontainers.image.vendor=Statistics Canada
            org.opencontainers.image.licenses=https://github.com/StatCan/ingress-istio-controller/blob/${{ env.GIT_SHA }}/LICENSE
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: statcan/ingress-istio-controller:${{ env.TAG }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=${{ env.TAG }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
